services:
  nginx:
    image: honeok/nginx:1.28.0-alpine3.21
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/php.conf:/etc/nginx/conf.d/php.conf
      - ./html:/var/www/html
    tmpfs:
      - /var/cache/nginx:rw,noexec,nosuid,size=512m
    networks:
      - callback

  php:
    image: registry.cn-chengdu.aliyuncs.com/havario/php-base:8.1.32-fpm-alpine3.21
    container_name: php
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
    networks:
      - callback

networks:
  callback:
    driver: bridge