---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "16:00"
    target-branch: "release"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"