services:
  nginx:
    image: registry.cn-chengdu.aliyuncs.com/honeok/nginx:1.27.4-alpine3.21
    container_name: bserver_nginx
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/bserver.conf:/etc/nginx/conf.d/bserver.conf
    tmpfs:
      - /var/cache/nginx:rw,noexec,nosuid,size=512m
    networks:
      - bserver

  bserver_1:
    image: registry.cn-chengdu.aliyuncs.com/havario/bserver
    container_name: bserver_1
    restart: unless-stopped
    volumes:
      - ./BattleSimulator:/bserver/BattleSimulator
      - ./logs:/bserver/logs
    networks:
      - bserver

  bserver_2:
    image: registry.cn-chengdu.aliyuncs.com/havario/bserver
    container_name: bserver_2
    restart: unless-stopped
    volumes:
      - ./BattleSimulator:/bserver/BattleSimulator
      - ./logs:/bserver/logs
    networks:
      - bserver

  bserver_3:
    image: registry.cn-chengdu.aliyuncs.com/havario/bserver
    container_name: bserver_3
    restart: unless-stopped
    volumes:
      - ./BattleSimulator:/bserver/BattleSimulator
      - ./logs:/bserver/logs
    networks:
      - bserver

networks:
  bserver:
    driver: bridge